### ISSUE TITLE
Colors are hard to read

### ISSUE THREAD

**Issue by jah2488** [tiy-austin-ror-jan2015/tiy-rails-template#26]
The background color makes it hard to read sometimes. Is the background color needed?

![screen shot 2015-02-19 at 3 32 33 pm](https://cloud.githubusercontent.com/assets/249209/6276468/a93ac0f2-b84c-11e4-91e3-8efb59a9c06f.png)

**Comment by Jmingus** [comment]
Oh my background is black, Ill change that

**Comment by Jmingus** [comment]
Background colors have been removed.
