### ISSUE TITLE
Remove unwanted files

### ISSUE THREAD

**Issue by jah2488** [tiy-austin-ror-jan2015/tiy-rails-template#28]
Currently the template repo has a `tester/` app and a `.DS_Store` file which should both be removed from the git repo.

Someone needs to fork the repo, clone the repo, delete the tester folder, delete the `.DS_Store` file, add those deletions to git, commit, push up, and create a pull request to merge those changes back in.

**Comment by Jmingus** [comment]
Unwanted files removed.
