### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by jah2488** [tiy-austin-ror-jan2015/tiy-rails-template#30]
A readme file is needed to describe what this template is and what it does.

The readme should outline a few things
- How to use the template
- What gems are created
- What steps the template does for you
- What steps the template **does not** do for you
- What steps need to be taken after
- What problems you may run into

**Comment by buckspencer** [comment]
@jah2488 I am currently working on this.

**Comment by jah2488** [comment]
@buckspencer Yayy

**Comment by jah2488** [comment]
@buckspencer finished this. It was closed with 05d7907
