### ISSUE TITLE
Add Devise to Template

### ISSUE THREAD

**Issue by Jmingus** [tiy-austin-ror-jan2015/tiy-rails-template#9]

**Comment by Jmingus** [comment]
Added the Devise gem and reminders for devise generator, still needs more

**Comment by jah2488** [comment]
Has this been added can you @kbalducci Verify that this is in the generator and close the issue if it has?

**Comment by kbalducci** [comment]
Devise gem is installed. Also, generator now runs devise:install and also generates the devise views. Directions are then given for the user to run: ~ rails generate devise MODEL
